### ISSUE TITLE
Fengardo regular v2?

### ISSUE THREAD

**Issue by adrientetar** [loicsander/Fengardo-Redux#1]
It seems both Fengardo regulars are the same file (version 1). The one with a 2 should have version two.

**Comment by adrientetar** [comment]
By the way what are the slightly different outlines on the background layers? Are these the original drawings or sth?

**Comment by loicsander** [comment]
If the two files seem to be identical, then it certainly a remainder of the duplicate-file system I used for backup, one of the two can be removed as git makes numbering files useless. 

As for the outlines on the background layers, they can be removed, they correspond to the last modifications I did to the outlines.

**Comment by adrientetar** [comment]
I see, thanks for the clarification!

**Comment by loicsander** [comment]
You’re welcome!
